# Programming Assignment 5
---
**Author:** John Little  
**Version:** 1.0  
**Semester:** Spring 2024 

### Problem 1 - Language Translator 

In [11]:
dictionary = { 
    'apple': 'manzana',
    'car': 'coche',
    'house': 'casa',
    'dog': 'perro',
    'cat': 'gato',
    'sun': 'sol',
    'moon': 'luna',
    'tree': 'árbol',
    'book': 'libro',
    'computer': 'computadora',
    'banana': 'plátano',
    'chair': 'silla',
    'table': 'mesa',
    'water': 'agua',
    'flower': 'flor',
    'bird': 'pájaro',
    'friend': 'amigo',
    'music': 'música',
    'food': 'comida',
    'love': 'amor'}

eng_word = input('Enter a word to translate from English to Spanish (enter Q to stop): ')

while eng_word != 'Q':
    if eng_word in dictionary:
        span_word = dictionary[eng_word]
        print(f"The Spanish word for '{eng_word}' is '{span_word}'.")
    else: 
        print(f"The Spanish word for '{eng_word}' is not in this dictionary.")
    eng_word = input('Enter a word to translate from English to Spanish (enter Q to stop): ')
print('Done!')


Enter a word to translate from English to Spanish (enter Q to stop):  table


The Spanish word for 'table' is 'mesa'.


Enter a word to translate from English to Spanish (enter Q to stop):  tree


The Spanish word for 'tree' is 'árbol'.


Enter a word to translate from English to Spanish (enter Q to stop):  potatoes 


The Spanish word for 'potatoes ' is not in this dictionary.


Enter a word to translate from English to Spanish (enter Q to stop):  Q


Done!


### Problem 2 - Translating Morse Code 

In [65]:
morse_dict = {
    'a': '.-',
    'b': '-...',
    'c': '-.-.',
    'd': '-..',
    'e': '.',
    'f': '..-.',
    'g': '--.',
    'h': '....',
    'i': '..',
    'j': '.---',
    'k': '-.-',
    'l': '.-..',
    'm': '--',
    'n': '-.',
    'o': '---',
    'p': '.--.',
    'q': '--.-',
    'r': '.-.',
    's': '...',
    't': '-',
    'u': '..-',
    'v': '...-',
    'w': '.--',
    'x': '-..-',
    'y': '-.--',
    'z': '--..',
    '0': '-----',
    '1': '.----',
    '2': '..---',
    '3': '...--',
    '4': '....-',
    '5': '.....',
    '6': '-....',
    '7': '--...',
    '8': '---..',
    '9': '----.'}

english = input('Enter a message in English (enter Q to stop): ')
def EngToMorse(english):
    while english != 'q':
        morse = ' '
        for character in english:
            if character in morse_dict:
                morse = morse + morse_dict[character] + ' '
            elif character == ' ':
                morse = morse + '   '
            else:
                print(f"Character {character} is not present in this dictionary")
        print(f"The morse code translation is: {morse}.")
        english = input('Enter a word to translate from English to Spanish (enter q to stop): ')
    print('Done!')

EngToMorse(english)


Enter a message in English (enter Q to stop):  no


The morse code translation is:  -. --- .


Enter a word to translate from English to Spanish (enter q to stop):  yes


The morse code translation is:  -.-- . ... .


Enter a word to translate from English to Spanish (enter q to stop):  i like redbull


The morse code translation is:  ..    .-.. .. -.- .    .-. . -.. -... ..- .-.. .-.. .


Enter a word to translate from English to Spanish (enter q to stop):  q


Done!


### Problem 3 - Comparing Minors/Majors

In [82]:
comp_sci = {'CS130', 'CS131', 'CS215'}
bus_admin = {'BUSA103', 'BUSA203', 'BUSA301', 'BUSA305', 'ACCT101', 'ECON110', 'FINA315', 'MATH117'}
bus_analytics = {'BUSA103', 'BUSA245', 'BUSA346', 'CS150', 'DS160', 'DS300', 'MATH117', 'MATH205'}
data_sci = {'BUSA103', 'BUSA245', 'BUSA346', 'CS150', 'DS160', 'DS300', 'DS450', 'MATH205', 'MATH215', 'MATH430', 'ECON410', 'ECON110', 'ECON111', 'MATH117'}

answer1 = bus_admin & bus_analytics
answer2 = bus_admin | comp_sci
answer3 = bus_admin - bus_analytics

## answer 4
if comp_sci & data_sci:
    answer4 = 'There are overlapping courses.'
else:
    answer4 = 'There are NOT overlapping courses.'

## answer 5 
subsumed_by_data_sci = True
for course in bus_analytics:
    if course not in data_sci:
        subsumed_by_data_sci = False
        
if subsumed_by_data_sci:
    answer5 = 'All Business Analytics courses are included in the Data Science major.'
else:
    answer5 = 'NOT all Business Analytics courses are included in the Data Science major.'

## print statements 
print(f"1. These courses overlap: {answer1}.")
print(f"2. They would have to take these courses: {answer2}.")
print(f"3. These courses are in the Business Administration minor, but not the Business Analytics minor: {answer3}")
print(f"4. {answer4}")
print(f"5. {answer5}")


    


1. These courses overlap: {'BUSA103', 'MATH117'}.
2. They would have to take these courses: {'CS215', 'CS130', 'FINA315', 'BUSA203', 'BUSA305', 'ACCT101', 'CS131', 'BUSA103', 'MATH117', 'ECON110', 'BUSA301'}.
3. These courses are in the Business Administration minor, but not the Business Analytics minor: {'FINA315', 'BUSA203', 'BUSA305', 'ACCT101', 'ECON110', 'BUSA301'}
4. There are NOT overlapping courses.
5. All Business Analytics courses are included in the Data Science major.


### Problem 4 - Working with NumPy

In [108]:
import random
import numpy as np
nums = np.random.randint(0,21, size=(5,5))
nums2 = np.random.randint(0,21, size=(5,5))

## part a 
matrix_product = nums*nums2
dot_product = np.dot(nums.flatten(),nums2.flatten())

## part b 
determinant_nums = np.linalg.det(nums)
determinant_nums2 = np.linalg.det(nums2)

inverse_nums = np.linalg.det(nums)
inverse_nums2 = np.linalg.det(nums2)

## part c 
nums3 = np.linspace(0.0,1.0, num=20)
nums4 = np.linspace(1.0,2.0, num=20)

combined_nums = np.hstack((nums3,nums4))
finished_nums = combined_nums.reshape(10,4)

### print statements 
## part a
print('Answers for part a')
print(f"The matrix product is \n{matrix_product}")
print(f"The dot product is {dot_product}")
print('  ')

## part b 
print('Answers for part b')
print(f"The determinant of the FIRST array is {determinant_nums}")
print(f"The inverse of the FIRST array is {inverse_nums}")
print(f"The determinant of the SECOND array is {determinant_nums2}")
print(f"The inverse of the SECOND array is {inverse_nums2}")
print('  ')

## part c 
print('Answer for part c')
print(f"Here is the concatenated and reshaped array: \n{finished_nums}")


Answers for part a
The matrix product is 
[[126 228   8  20  88]
 [108   5 104 144   0]
 [228  60  12 270  32]
 [154 285  90 114   0]
 [170 108 195 190 105]]
The dot product is 2844
  
Answers for part b
The determinant of the FIRST array is 195204.99999999983
The inverse of the FIRST array is 195204.99999999983
The determinant of the SECOND array is -245163.99999999997
The inverse of the SECOND array is -245163.99999999997
  
Answer for part c
Here is the concatenated and reshaped array: 
[[0.         0.05263158 0.10526316 0.15789474]
 [0.21052632 0.26315789 0.31578947 0.36842105]
 [0.42105263 0.47368421 0.52631579 0.57894737]
 [0.63157895 0.68421053 0.73684211 0.78947368]
 [0.84210526 0.89473684 0.94736842 1.        ]
 [1.         1.05263158 1.10526316 1.15789474]
 [1.21052632 1.26315789 1.31578947 1.36842105]
 [1.42105263 1.47368421 1.52631579 1.57894737]
 [1.63157895 1.68421053 1.73684211 1.78947368]
 [1.84210526 1.89473684 1.94736842 2.        ]]
